setwd("C:/Users/hu/Desktop/data-berka")
trans       <-  read.csv("trans.csv", sep = ";")
Ans2a       <-  subset(trans,(amount >= 10000) & (amount %% 100 == 0))  
Ans3a       <-  subset(trans,(amount >= 9000) & (amount <= 10000))
userFrein2a <-  table(Ans2a$account_id)
Ans2b       <-  subset(as.data.frame(userFrein2a),Freq >= 2)
userFrein3a <-  table(Ans3a$account_id)
Ans3b       <-  subset(as.data.frame(userFrein3a),Freq >= 3)
Ans2a$true  <-  is.element(Ans2a$account_id,Ans2b$Var1)
Ans2c       <-  subset(Ans2a,true == TRUE)
Ans3a$true  <-  is.element(Ans3a$account_id,Ans3b$Var1)
Ans3c       <-  subset(Ans3a,true == TRUE)
Mon2d       <-  subset(Ans2a,(date >= 980501) & (date <= 980531))
MonFre2d    <-  table(Mon2d$account_id)
user2d      <-  subset(as.data.frame(MonFre2d),Freq >= 2)
Mon2d$true  <-  is.element(Mon2d$account_id,user2d$Var1)
Ans2d       <-  subset(Mon2d,true == TRUE)
Mon3d       <-  subset(Ans3a,(date >= 980501) & (date <= 980531))
MonFre3d    <-  table(Mon3d$account_id)
user3d      <-  subset(as.data.frame(MonFre3d),Freq >= 3)
Mon3d$true  <-  is.element(Mon3d$account_id,user3d$Var1) 
Ans3d       <-  subset(Mon3d,true == TRUE)

